### ISSUE TITLE
Multimonitor inconvenience issue

### ISSUE THREAD

**Issue by AlexeyKryshen** [RealFatCat/hot-translate#4]
Hello,

I use multimonitor configuration and run Firefox on secondary monitor. The problem (well, not actual the problem but some kind of inconvenience) is that translation notifications (via the Alt-Q) appear on primary monitor, which is really not very convenient. It would be nice to have (maybe via the configurable option) translation pop-up appear in the Firefox window itself (close to selection or just at some corner or in toolbox or anything else but inside the Firefox window frame.

Beside of this, so far, the plugin looks pretty good. Thank you!

**Comment by RealFatCat** [comment]
HI.
First of all, thanks for reply.
For now I use 'notifications' lib, provided by mozilla addon sdk. This API uses OS-based notifiactions. That's why you see translation on another monitor - because notification area is there.
I thougth about showing pop-up near selected text, but seems like there is now simple way to do this.
In fact, I wanted to do this plugin as simple as it possible, so we got what we got.
